version: '3.3'
services:
  host1:
    image: arvindr226/alpine-ssh
    ports:
      - "22"
  host2:
    image: arvindr226/alpine-ssh
    ports:
      - "22"
  host3:
    image: arvindr226/alpine-ssh
    ports:
      - "22"
  host4:
    image: arvindr226/alpine-ssh
    ports:
      - "22"
  host5:
    image: arvindr226/alpine-ssh
    ports:
      - "22"
  db1:
    image: scylladb/scylla
    ports:
      - "9042"
    # Allow seeding DB using `docker-compose exec db1 cqlsh -e "SOURCE '/tmp/seed.cql'"`
    volumes:
      - ./db/seed.cql:/tmp/seed.cql
  db2:
    image: scylladb/scylla
    ports:
      - "9042"
    command: --seeds db1
  db3:
    image: scylladb/scylla
    ports:
      - "9042"
    command: --seeds db1
  worker1:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    ports:
      - "8888"
  worker2:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    ports:
      - "8888"
  worker3:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    ports:
      - "8888"
  master:
    depends_on:
      - host1
      - host2
      - host3
      - host4
      - host5
      - db1
      - worker1
      - worker2
      - worker3
    build:
      context: .
      dockerfile: ./docker/master/Dockerfile
    command: /wait-for.sh db1:9042 -- /master --db-hosts db1,db2,db3 --workers worker1:8888,worker2:8888,worker3:8888
    volumes:
      - ./ssh_keys:/etc/simple-cm/keys