version: '3'
services:
  host1:
    image: arvindr226/alpine-ssh
    ports:
      - "22:2221"
  db:
    image: cassandra
    ports:
      - "9042:9042"
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    ports:
      - "8888"
  master:
    depends_on:
      - host1
      - db
      - worker
    build:
      context: .
      dockerfile: ./docker/master/Dockerfile
    command: /wait-for.sh db:9042 -- /master --db-hosts db --workers worker:8888
    volumes:
      - ./ssh_keys:/etc/simple-cm/keys