apiVersion: v1
kind: Service
metadata:
  name: hosts
  labels:
    app: hosts
spec:
  ports:
  - port: 22
    name: ssh
  clusterIP: None
  selector:
    app: hosts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: host
spec:
  serviceName: "hosts"
  replicas: 5
  selector:
    matchLabels:
      app: hosts
  template:
    metadata:
      labels:
        app: hosts
    spec:
      containers:
      - name: host
        image: arvindr226/alpine-ssh
        ports:
        - containerPort: 22
          name: ssh