apiVersion: v1
kind: Service
metadata:
  name: workers
  labels:
    app: workers
spec:
  ports:
  - port: 8888
    name: rpc
  clusterIP: None
  selector:
    app: workers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  labels:
    app: workers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
      - name: worker
        image: quay.io/jlieb/simple-cm-worker
        ports:
        - containerPort: 8888